FROM registry.access.redhat.com/ubi9/nodejs-18-minimal:latest AS builder

USER 0
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

FROM registry.access.redhat.com/ubi9/nodejs-18-minimal:latest

USER 0
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY server.js package.json ./

EXPOSE 3001

CMD ["node", "server.js"]
